# Generated by Django 2.2 on 2019-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('gps_cordinates', models.CharField(max_length=100, unique=True)),
                ('demographic_data', models.CharField(max_length=100)),
                ('satelite_images', models.FileField(upload_to='Satelite_images')),
                ('news_articles', models.TextField()),
                ('geo_data', models.CharField(max_length=1000)),
            ],
        ),
    ]
