# Generated by Django 2.2 on 2019-09-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='gps_cordinates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='satelite_images',
            field=models.FileField(blank=True, upload_to='Satelite_images'),
        ),
    ]
